#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four 
# million, find the sum of the even-valued terms.
fibA = 1
fibB = 2
fibC = fibA + fibB
sumofevens = fibB
themax = 4000000
while fibC < themax:
    fibC = fibA + fibB
    if fibC % 2 == 0:
        sumofevens = sumofevens + fibC
    fibA = fibB
    fibB = fibC
print(sumofevens)
   